import '@/app/globals.css';

export const metadata = {
  title: 'book bus',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white' >{children}</body>
    </html>
  )
}
